### ISSUE TITLE
Wrong entitlements in v0.7.0

### ISSUE THREAD

**Issue by RuyeNet** [sohsatoh/ReProvision-Reborn#1] opened 2021-08-16 04:52 UTC
Wrong certificate used in v0.7.0

1.Go to 'iPhone Setting – General – Description File'
2.Click on the description file generated by ReProvision-Reborn

**Expected behavior**
At ReProvision-Reborn version 0.6.x，The certificate name is“iPhone Developer:example@example.com”，
But At ReProvision-Reborn version 0.7.0，The certificate name is“Apple Development:example@example.com”.
This will cause unc0ver to fail to jailbreak,It throws an error like this “An error occurred while verifying the entitlements of our application. This build was signed improperly. Please install the build with official methods from https://unc0ver.dev and try again.”
I think there is a problem with the certificate used for the signature.

**Screenshots**
![correct](https://user-images.githubusercontent.com/31236859/129512786-00f340d3-7e95-4a51-845c-a8777d74d865.jpg)

Error: **Reducted** as it contains a e-mail address associated with apple id

**Device (please complete the following information):**
 - iOS 14.3
- iPhone 11 and iPhone 11 Pro Max (I used two devices for testing)

**Comment by sohsatoh** [comment] 2021-08-16 06:05
The cert should have absolutely nothing to do with how it works with u0.
The problem is caused by entitlements and that will be fixed.
If you even remove it and sign u0 with v0.6.x RR, the jailbreaking process with u0 should still fail.
Just in case, please try that and report the result.

**Comment by RuyeNet** [comment] 2021-08-16 07:04
> The cert should have absolutely nothing to do with how it works with u0.
> The problem is caused by entitlements and that will be fixed.
> If you even remove it and sign u0 with v0.6.x RR, the jailbreaking process with u0 should still fail.
> Just in case, please try that and report the result.

I used two devices to test again and got the following results:
Use the 0.6.x version to sign unc0ver, and the jailbreak is successful;
Use the 0.7.0 version to sign unc0ver, and the jailbreak fails.
Error alert:“ An error occurred while verifying the entitlements of our application. This build was signed improperly. ”

**Comment by sohsatoh** [comment] 2021-08-16 09:50
Thanks! It is probably because of the entitlements are embedded in provisioning profile on the Apple server.
Could you try these instructions?

1. Uninstall u0 from profile menu (the screen in the pic you attached)
2. Open ReProvision and logout from your Apple ID
3. Login with **another Apple ID**
4. Sign and Install u0 from IPA

**Comment by RuyeNet** [comment] 2021-08-16 10:25
> Thanks! It is probably because of the entitlements are embedded in provisioning profile on the Apple server.
> Could you try these instructions?
> 
> 1. Uninstall u0 from profile menu (the screen in the pic you attached)
> 2. Open ReProvision and logout from your Apple ID
> 3. Login with **another Apple ID**
> 4. Sign and Install u0 from IPA

<html>
<body>
<!DOCTYPE html><figure class="md-table-fig" cid="n2" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

  | Apple ID A | Apple ID B | Apple ID C | Apple ID D
-- | -- | -- | -- | --
RR v0.6.2 on iPhone 11 | Success | Success | Success | Success
RR v0.7.0 on iPhone 11 | Failed | Failed | Failed | Failed
RR v0.6.2 on iPhone 11 Pro Max | Success | Success | Success | Success
RR v0.7.0 on iPhone 11 Pro Max | Failed | Failed | Failed | Failed

</figure><p cid="n18" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">I tried the following methods:</span></p><p cid="n22" mdtype="paragraph" class="md-end-block md-p md-focus" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain md-expand" style="box-sizing: border-box;">1.Uninstall u0 from profile menu</span></p><p cid="n31" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">2.Tried 4 Apple IDs on two devices</span></p><p cid="n39" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">3.Download the ipa file from u0 official website, and then use RR to sign</span></p><p cid="n42" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">But the problem still exists.</span></p><p cid="n58" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p><p cid="n63" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">As you said,the problem is caused by entitlements.(unc0ver threw this error)</span></p><p cid="n60" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">When there is a problem, the profile menu will start with "Apple Development:" instead of "iPhone Developer:".</span></p><p cid="n65" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p><p cid="n67" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Since the release of Reprovision Reborn, I have been using it on two devices, and this problem appeared after updating to v0.7.0.</span></p><p cid="n48" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p><p cid="n69" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">I also downgraded to RR v0.6.2 and the problem was solved.</span></p><p cid="n45" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">After many attempts, it is determined that the problem is caused by RR v0.7.0.</span></p>
</body>
</html>

**Comment by sohsatoh** [comment] 2021-08-16 14:25
Thank you for the information.
I tried with my Apple ID, but u0 does not show any alerts.
Seems like I have to look for people who can test the new debug build.
![D626578E-7883-4E75-88EB-5BF20D05BC49](https://user-images.githubusercontent.com/20023945/129579258-c080d74f-8526-4f75-b840-0adeaf920417.png)
![2821370A-D229-4562-9AEB-FD2E33E0E340](https://user-images.githubusercontent.com/20023945/129579403-ba95fdce-55b2-4d40-beb8-be771891653b.jpeg)

**Comment by RuyeNet** [comment] 2021-08-16 16:57
Like this, Don't care about the version of u0 in the picture, I also tried u0 v6.2.0, the same error.
![6EF2EB8D-30C0-4B2F-AD80-70098D9DFE37](https://user-images.githubusercontent.com/31236859/129601134-6a54cdf3-1ddb-4649-96a2-1da649ef39b5.jpeg)

**Comment by RuyeNet** [comment] 2021-08-16 17:07
Thank you very much.
In order to avoid this problem, I have downgraded RR to v0.6.2, maybe we should wait for others to report this problem.

**Comment by Steppen-wolf** [comment] 2021-08-16 23:33
Same here!
iOS 14.2 iPhone XR 
Unc0ver 6.1.1
Back to Reprovision v0.6.2 solved this trouble. 

Tx for your work!

**Comment by sohsatoh** [comment] 2021-08-17 07:17
@Ruyenet Could you check the entitlements of u0 signed by RR v0.6.2 and v0.7.0 using ldid?

Command: `ldid -e <the path of the binary of u0 on iOS>`

**Comment by RuyeNet** [comment] 2021-08-17 12:56
> @Ruyenet Could you check the entitlements of u0 signed by RR v0.6.2 and v0.7.0 using ldid?
> 
> Command: `ldid -e <the path of the binary of u0 on iOS>`

Of course, please wait some time.

**Comment by RuyeNet** [comment] 2021-08-17 14:42
Doesn't seem to make a difference.

----------------------------------------------------------------------------------------------------

RR 0.6.2

```
iPhone-11-Pro-Max:~ root# ldid -e /private/var/containers/Bundle/Application/CBAA10A3-49CD-45E9-B19E-B45193230FE2/unc0ver.app/unc0ver 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>application-identifier</key>
	<string>Reducted.science.xnu.undecimus.Reducted</string>
	<key>com.apple.developer.team-identifier</key>
	<string>Reducted</string>
	<key>keychain-access-groups</key>
	<array>
		<string>Reducted.*</string>
	</array>
</dict>
</plist>
```




----------------------------------------------------------------------------------------------------

RR0.7.0

```
iPhone-11-Pro-Max:~ root# ldid -e /private/var/containers/Bundle/Application/B9B34011-3EC0-4543-BBEF-5C2637114BFB/unc0ver.app/unc0ver 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>application-identifier</key>
	<string>Reducted.science.xnu.undecimus.Reducted</string>
	<key>com.apple.developer.team-identifier</key>
	<string>Reducted</string>
	<key>keychain-access-groups</key>
	<array>
		<string>Reducted.*</string>
	</array>
</dict>
</plist>
```

**Comment by RuyeNet** [comment] 2021-08-17 14:46
I execute ldid on the iPhone terminal. Is my operation correct?
![IMG_1640](https://user-images.githubusercontent.com/31236859/129747864-50a757c6-6565-4b3f-bbbb-2579d3255175.PNG)

**Comment by sohsatoh** [comment] 2021-08-17 17:21
@Ruyenet Thanks, that information is really useful!
Could you try installing v0.8.0, uninstall and re-install (re-sign) u0, and run the same command? (This is debug build so not for release)
https://github.com/sohsatoh/ReProvision-Reborn/releases

Anyway, is il****@ilove*.top is your apple paid developer account?
If so, the issue is probably caused by this commit.
https://github.com/sohsatoh/ReProvision-Reborn/commit/a134df06b4b7eeb8b4c3aaee089f41506a8cf9de

**Comment by RuyeNet** [comment] 2021-08-17 23:22
All my Apple IDs are free accounts, and the signature is only valid for 7 days. I did not purchase any developer accounts.

**Comment by RuyeNet** [comment] 2021-08-18 00:01
I tested with v0.8.0 on two devices and the problem has been resolved.
Thanks for your work!

**Comment by sohsatoh** [comment] 2021-08-18 03:37
Great to hear that!
Thanks for testing!

**Closed as completed by sohsatoh** 2021-08-18 03:37 UTC
